baseURL = 'https://mpdabrowski.github.io/'
languageCode = 'en-us'
theme = 'hyde'
title = 'Michał P. Dąbrowski'
publishDir = "public"
[Menus]
  main = [
      {Name = "Github ↗", URL = "https://github.com/mpdabrowski/"},
      {Name = "LinkedIn ↗", URL = "https://www.linkedin.com/in/michal-dabrowski98//"}
  ]
[params]
  description = "Jestem programistą z kilkuletnim doświadczeniem. Interesuję się sztuczną inteligencją."
  themeColor = "theme-base-0b"
  
[[module.mounts]]
source = 'static'
target = 'static'

[[module.mounts]]
source = 'images'
target = 'static/images'